### ISSUE TITLE
After config the plugin, octoprint can't start

### ISSUE THREAD

**Issue by karug** [ziirish/OctoPrint-TuyaSmartplug#54]
In the log i see this:
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/server/api/__init__.py", line 158, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_tuyasmartplug/__init__.py", line 258, in on_api_command
    self.check_status("{label}".format(**data))
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_tuyasmartplug/__init__.py", line 229, in check_status
    "on" if self.is_turned_on(response, pluglabel) else "off"
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_tuyasmartplug/__init__.py", line 242, in is_turned_on
    return data and plug and data.get("dps", {}).get(str(plug["slot"]))

**Comment by karug** [comment]
I show that the config.yml only have this config:

- _count: 12
  _timestamp: 1683885946.961225
  base_url: http://ender/
  path: /
  query_string: l10n=en
- _count: 10
  _timestamp: 1683321650.5123067
  base_url: http://192.168.0.101/
  path: /
  query_string: l10n=en
